# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 71b44cefdbbc6f10c3998890f43499aebbf0cea2310c9c2be7bcff52e6cfddcac605f7907980654512e415ab1a97ca66d71d7d7595dfe9347012572f1275b6c8

test:
  secret_key_base: 27b133b4691d66902c155a688e3711bd36b3566ce7337a67b776191fda53397351a05c68ae42361ebf748423255c8020636cbdea88a489dd9a248e363e3fdc55

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
